name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: faisal2

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push web-show-results
        run: |
          docker build -t ${{ env.IMAGE_PREFIX }}/web-show-results:${{ github.sha }} ./web-show-results
          docker push ${{ env.IMAGE_PREFIX }}/web-show-results:${{ github.sha }}
          docker tag ${{ env.IMAGE_PREFIX }}/web-show-results:${{ github.sha }} ${{ env.IMAGE_PREFIX }}/web-show-results:latest
          docker push ${{ env.IMAGE_PREFIX }}/web-show-results:latest

      - name: Build and push web-enter-data
        run: |
          docker build -t ${{ env.IMAGE_PREFIX }}/web-enter-data:${{ github.sha }} ./web-enter-data
          docker push ${{ env.IMAGE_PREFIX }}/web-enter-data:${{ github.sha }}
          docker tag ${{ env.IMAGE_PREFIX }}/web-enter-data:${{ github.sha }} ${{ env.IMAGE_PREFIX }}/web-enter-data:latest
          docker push ${{ env.IMAGE_PREFIX }}/web-enter-data:latest

      - name: Build and push analysis
        run: |
          docker build -t ${{ env.IMAGE_PREFIX }}/analysis:${{ github.sha }} ./analysis
          docker push ${{ env.IMAGE_PREFIX }}/analysis:${{ github.sha }}
          docker tag ${{ env.IMAGE_PREFIX }}/analysis:${{ github.sha }} ${{ env.IMAGE_PREFIX }}/analysis:latest
          docker push ${{ env.IMAGE_PREFIX }}/analysis:latest

      - name: Build and push authentication
        run: |
          docker build -t ${{ env.IMAGE_PREFIX }}/authentication:${{ github.sha }} ./authentication
          docker push ${{ env.IMAGE_PREFIX }}/authentication:${{ github.sha }}
          docker tag ${{ env.IMAGE_PREFIX }}/authentication:${{ github.sha }} ${{ env.IMAGE_PREFIX }}/authentication:latest
          docker push ${{ env.IMAGE_PREFIX }}/authentication:latest

      - name: Build and push nginx-proxy
        run: |
          docker build -t ${{ env.IMAGE_PREFIX }}/nginx-proxy:${{ github.sha }} ./nginx-proxy
          docker push ${{ env.IMAGE_PREFIX }}/nginx-proxy:${{ github.sha }}
          docker tag ${{ env.IMAGE_PREFIX }}/nginx-proxy:${{ github.sha }} ${{ env.IMAGE_PREFIX }}/nginx-proxy:latest
          docker push ${{ env.IMAGE_PREFIX }}/nginx-proxy:latest

  
